import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Women's Black Jacket",
    categoryName: "women",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Men's Black Trouser",
    categoryName: "men",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Women's Black Trouser",
    categoryName: "women",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Men's Black shirt",
    categoryName: "men",
    ratings: 2,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Women's Black shirt",
    categoryName: "women",
    ratings: 2,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Men's Green Jacket",
    categoryName: "men",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Women's Green Jacket",
    categoryName: "women",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Men's Red t-shirt",
    categoryName: "men",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "https://picsum.photos/id/1/200/300",
  },
  {
    _id: uuid(),
    name: "Women's Red t-shirt",
    categoryName: "women",
    ratings: 3,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "",
  },
  // -------------------------------------------------------------------
  // ---------------------------------------------------
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "2000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "400",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "1000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "boys",
    ratings: 4,
    price: "5000",
    discountedPrice: "5000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "girls",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "",
  },
  {
    _id: uuid(),
    name: "Men's Black Jacket",
    categoryName: "men",
    ratings: 4,
    price: "5000",
    discountedPrice: "4000",
    discount: "20%",
    img: "",
  },
];
